image: maven:3-jdk-11

stages:
    - build
    - test
    - image

services:
   - name: docker:18-dind
     alias: thedockerhost

variables:
    DOCKER_HOST: tcp://thedockerhost:2375/
    # Use the overlayfs driver for improved performance:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

#Build stage
buildUserGateway:
    stage: build
    script:
        - cd userGateway
        - mvn package -Dmaven.test.skip=true

#Test stage
testUserGateway:
    stage: test
    script:
        - cd userGateway
        - mvn test

#Build and push docker image
imageUserGateway:
    stage: image
    image: docker:18-dind
    script: 
        - cd userGateway
        - docker build . -t timgroenen/kwetterusergateway
        - docker login --username $dockerUsername --password $dockerPassword
        - docker push timgroenen/kwetterusergateway